---
# Copy the GPO-Template file from the control host to the remote host. Note that the
# GPO-template file shall be a packed file and shall include the ADMX-files in the root
# and the ADML-files in subdirectories, such as: "de-DE" or "en-US"
- name: "[GPO] - Create Temporary Directories to download templates to."
  ansible.builtin.file:
    path: "/tmp/{{ item | basename }}"
    owner: root
    group: root
    mode: "0644"
    state: directory
  loop: "{{ sambadc_gpo_template }}"
  when: sambadc_gpo_template is defined
  tags:
    - gpo

- name: "[GPO] - Copy or Download Archive to Temporary Directory."
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
    owner: root
    group: root
    mode: "0664"
  loop: "{{ sambadc_gpo_template }}"
  when: sambadc_gpo_template is defined
  tags:
    - gpo

# Install the GPO-templates into samba-sysvol with the aid of samba-tool.
# Source: https://wiki.samba.org/index.php/Group_Policy
# First install the ADMX templates that come with samba.
- name: "[GPO] - Install ADMX-Templates that come with samba first."
  ansible.builtin.command: >
    samba-tool gpo admxload -H "{{ sambadc_fqdn }}" -U Administrator --password="{{ sambadc_admin_password }}"
  changed_when: true
  tags:
    - gpo

- name: "[GPO] - Install configured GPO-Templates."
  ansible.builtin.command: >
    samba-tool gpo admxload -H "{{ sambadc_fqdn }}" -U Administrator
      --password="{{ sambadc_admin_password }}"
      --admx-dir="/tmp/{{ item | basename }}"
  changed_when: true
  loop: "{{ sambadc_gpo_template }}"
  when: sambadc_gpo_template is defined
  tags:
    - gpo

# Delete the temporary files.
- name: "[GPO] - Delete temporary files and directories."
  ansible.builtin.file:
    path: "/tmp/{{ item | basename }}"
    state: absent
  loop: "{{ sambadc_gpo_template }}"
  when: sambadc_gpo_template is defined
  tags:
    - gpo

# Copy and Install configured Group Policies.
# Retriev the group Group Policies via command: samba-tool gpo backup <gpo>
# <gpo> can be obtained through samba-tool gpo listall
# The such retrieved GPO is copied to /tmp/*. Pack the files into a *.ZIP
# archive where GPTini.xml file shall be in the root and not in a subdirectory.
- name: "[GPO] - Create Temporary Directories to dowload Group Policies to."
  ansible.builtin.file:
    path: "/tmp/{{ item | basename }}"
    owner: root
    group: root
    mode: "0644"
    state: directory
  loop: "{{ sambadc_gpo }}"
  when: sambadc_gpo is defined
  tags:
    - gpo

- name: "[GPO] - Copy or Download Archive copntaining the Group Policy to Temporary Directory."
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
    owner: root
    group: root
    mode: "0664"
  loop: "{{ sambadc_gpo }}"
  when: sambadc_gpo is defined
  tags:
    - gpo

# samba-tool backup does not save the displayname attribute, this name is extracted
# from the filename.
# sambatool restore - for whatever reason - does require to provide a displayName, which
# is here used as a workaround.
- name: "[GPO] - Install configured Group Policies."
  ansible.builtin.command: >
    samba-tool gpo restore "{{ item | basename | split('.') | first }}" "/tmp/{{ item | basename }}"
      -H "{{ sambadc_fqdn }}" -U Administrator
      --password="{{ sambadc_admin_password }}"
  loop: "{{ sambadc_gpo }}"
  changed_when: true
  failed_when: false
  when: sambadc_gpo is defined
  tags:
    - gpo

- name: "[GPO] - Delete temporary files and directories."
  ansible.builtin.file:
    path: "/tmp/{{ item | basename }}"
    state: absent
  loop: "{{ sambadc_gpo }}"
  when: sambadc_gpo is defined
  tags:
    - gpo

# Activate the GPO's by linking to them. First, obtain the UUID to
# displayname-mapping for each GPO.
- name: "[GPO] - Obtain GPO displayname to UUID-mapping (1/2)."
  ansible.builtin.command: >
    samba-tool gpo listall
#      -H "{{ sambadc_fqdn }}" -U Administrator
#      --password="{{ sambadc_admin_password }}"
  changed_when: false
  register: df_cmd
  when: sambadc_gpo_activate is defined
  tags:
    - gpo

- name: "[GPO] - Obtain GPO displayname to UUID-mapping (2/2)."
  ansible.builtin.set_fact:
    keynames: "{{ df_cmd.stdout_lines | select('search', 'display name') | reverse | map('regex_replace', '.*:', '') | map('trim') }}"
    values: "{{ df_cmd.stdout_lines | select('search', 'GPO') | reverse | map('regex_replace', '.*:', '') | map('trim') }}"
  when: sambadc_gpo_activate is defined
  tags:
    - gpo

# - name: "[GPO] - Activate configured Group Policies."
#   ansible.builtin.debug:
#     msg: "{{ dict(keynames | zip(values)) }}"
#   when: sambadc_gpo_activate is defined
#   tags:
#     - gpo

- name: "[GPO] - Activate configured Group Policies."
  ansible.builtin.command: >
    samba-tool gpo setlink "{{ sambadc_ldap }}" "{{ gpo_mapping[item] }}"
      -U Administrator --password="{{ sambadc_admin_password }}"
  changed_when: true
  loop: "{{ sambadc_gpo_activate }}"
  when: sambadc_gpo_activate is defined
  vars:
    gpo_mapping: "{{ dict(keynames | zip(values)) }}"
  tags:
    - gpo
