---
# Get the interface, so that IPv4 and IPv6 adresse for Reverse-lookup can be extracted.
# The adresses are used to put together an PTR-record.
# Currently IPv6 implementation needs to be completed.
# IPv4 may also need some revision for e.g. 192.168.0.0/16 subnets the PTR may lack a leading zero.
- name: "[NAMED] - Build the IPv4 & IPv6 PTR-record."
  ansible.builtin.set_fact:
    ipv4net: "{{ iface.ipv4.network | replace('.0', '') + '.' }}"
    ipv4ptr: "{{ iface.ipv4.network | ansible.utils.ipaddr('revdns') | replace('0.', '') }}"
    ipv6ptr: "{{ iface.ipv6[0].address | ansible.utils.ipaddr('revdns') }}"
  tags:
    - dns_bind_dlz

- name: "[NAMED] - Extract Host Subnet-Address."
  ansible.builtin.set_fact:
    ipv4host: "{{ iface.ipv4.address | replace(ipv4net, '') }}"
  tags:
    - dns_bind_dlz

# - name: "[NAMED] - Switch DNS-backend to BIND9_DLZ."
#   ansible.builtin.command: samba_upgraddns --dns-backend=BIND9_DLZ
#   ansible.builtin.command: samba_upgraddns --dns-backend=SAMBA_INTERNAL
#   ansible.builtin.lineinfile:
#   when: ansible_run_tags in ["BIND9_DLZ"]
#   when: ansible_run_tags in ["SAMBA_INTERNAL"]

# Source: https://bugzilla.samba.org/show_bug.cgi?id=14535
# Fixes an issue that existed in pre 4.15 versions.
- name: "[NAMED] - Copy dns.keytab (bugfix for 14535)."
  ansible.builtin.copy:
    src: "{{ PRIVATE_DIR }}/dns.keytab"
    dest: "{{ BINDDNS_DIR }}"
    owner: root
    group: bind
    mode: "0644"
    remote_src: true
  when: sambadc_version.stdout is not match("14")
  tags:
    - dns_bind_dlz

# Do all the changes to /etc/bind/named.conf.options
- name: "[NAMED] - Modify named.conf.options."
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.options
    block: |
           #
                   # https://wiki.samba.org/index.php/BIND9_DLZ_DNS_Back_End#Setting_up_BIND9_options_and_keytab_for_Kerberos
                   forwarders {
                     {{ sambadc_forwarder }};
                   };
                   tkey-gssapi-keytab "{{ BINDDNS_DIR }}/dns.keytab";
                   minimal-responses yes;
    insertafter: '// };'
  tags:
    - dns_bind_dlz

- name: "[NAMED] - Change DNSSEC to \"no\"."
  ansible.builtin.replace:
    path: /etc/bind/named.conf.options
    regexp: 'dnssec-validation auto;'
    replace: 'dnssec-validation no;'
  tags:
    - dns_bind_dlz

# Do all the changes to /etc/bind/named.conf.local
- name: "[NAMED] - Modify named.conf.local."
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.local
    block: |
           include "{{ BINDDNS_DIR }}/named.conf";
  tags:
    - dns_bind_dlz

# Finally uncomment in /var/lib/samba/bind-dns/named.conf the lib corresponding to the named version.
- name: "[NAMED] - Uncomment in BINDDNS_DIR the respective version in named.conf-file."
  ansible.builtin.replace:
    dest: "{{ BINDDNS_DIR }}/named.conf"
    regexp: "{{ '^(\\s*)#(.*' + sambadc_bindversion[0] + '_' + sambadc_bindversion[1] + '.*)$' }}"
    replace: '\1\2'
  tags:
    - dns_bind_dlz

# Create Reverse zone and associated entry for Reverse resolution on host.
- name: "[NAMED] - Add a Reversezone."
  ansible.builtin.command: >
    samba-tool dns zonecreate localhost {{ ipv4ptr }} -U Administrator
  args:
    stdin: "{{ sambadc_admin_password }}"
  changed_when: (df_cmd.rc == 0)
  failed_when: (df_cmd.rc != 0) and ((df_cmd.stderr | lower) is not search("exists"))
  register: df_cmd
  tags:
    - dns_bind_dlz

- name: "[NAMED] - Add the host to the Reversezone."
  ansible.builtin.command: >
    samba-tool dns add localhost {{ ipv4ptr }} {{ ipv4host }} PTR {{ sambadc_fqdn }} -U Administrator
  args:
    stdin: "{{ sambadc_admin_password }}"
  changed_when: (df_cmd.rc == 0)
  failed_when: (df_cmd.rc != 0) and ((df_cmd.stderr | lower) is not search("exists"))
  register: df_cmd
  tags:
    - dns_bind_dlz

# Start checking filesystem-permissions for bind9
- name: "[NAMED] - Set file permissions for the bind-files that Samba created during provisioning (bugfix 14535)."
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: root
    group: bind
    mode: "{{ item.mode }}"
  tags:
    - dns_bind_dlz
  loop:
    - { path: "{{ BINDDNS_DIR }}", state: "directory", mode: "0770" }
    - { path: "{{ BINDDNS_DIR }}/dns", state: "directory", mode: "0770" }
    - { path: "{{ BINDDNS_DIR }}/dns/sam.ldb.d", state: "directory", mode: "0770" }
    - { path: "{{ BINDDNS_DIR }}/dns.keytab", state: "file", mode: "0640" }
    - { path: "{{ BINDDNS_DIR }}/dns/sam.ldb", state: "file", mode: "0660" }

- name: "[NAMED] - Listing files in BINDDNS_DIR/dns/sam.ldb.d/"
  ansible.builtin.find:
    paths: "{{ BINDDNS_DIR }}/dns/sam.ldb.d/"
    file_type: file
    patterns: "*"
  register: db_files
  tags:
    - dns_bind_dlz

- name: "[NAMED] - Checking permission for BINDDNS_DIR/dns/sam.ldb.d/* ."
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: file
    owner: root
    group: bind
    mode: "0660"
  tags:
    - dns_bind_dlz
  loop: "{{ db_files.files }}"

- name: "[NAMED] - Checking configuration file."
  ansible.builtin.command: named-checkconf
  changed_when: false
  tags:
    - dns_bind_dlz

# Restart bind9 after setting up the domain
- name: "[NAMED] - Restart bind9 Daemon."
  ansible.builtin.service:
    name: named
    state: restarted
  tags:
    - dns_bind_dlz
