---
# Source: https://bugzilla.samba.org/show_bug.cgi?id=14535
# Fixes an issue that existed in pre 4.15 versions.
- name: "[NAMED] - Copy dns.keytab (bugfix for 14535)."
  ansible.builtin.copy:
    src: "{{ PRIVATE_DIR }}/dns.keytab"
    dest: "{{ BINDDNS_DIR }}"
    owner: root
    group: bind
    mode: "0644"
    remote_src: true
  when: "'14.14' in sambadc_version.stdout"

# Do all the changes to /etc/bind/named.conf.options
- name: "[NAMED] - Modify named.conf.options"
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.options
    block: |
           forwarders {
             {{ sambadc_forwarder }};
           };
           tkey-gssapi-keytab "{{ BINDDNS_DIR }}/dns.keytab";
    insertafter: '// };'

- name: "[NAMED] - Change DNSSEC to \"no\""
  ansible.builtin.replace:
    path: /etc/bind/named.conf.options
    regexp: 'dnssec-validation auto;'
    replace: 'dnssec-validation no;'

# Do all the changes to /etc/bind/named.conf.local
- name: "[NAMED] - Modify named.conf.local"
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.local
    block: |
           include "{{ BINDDNS_DIR }}/named.conf";

# Create Reverse zone and associated entry for Reverse resolution on host.
- name: "[NAMED] - Add a Reversezone."
  ansible.builtin.command: >
    samba-tool dns zonecreate localhost 1.168.192.in-addr.arpa -U Administrator --password={{ sambadc_admin_password }}
  changed_when: true
  tags:
    - named

- name: "[NAMED] - Add the host to the Reversezone."
  ansible.builtin.command: >
    samba-tool dns add localhost 1.168.192.in-addr.arpa 130 PTR {{ sambadc_fqdn }} -U Administrator --password={{ sambadc_admin_password }}
  changed_when: true
  tags:
    - named

# - name: "[NAMED] - Add a Reversezone."
#  ansible.builtin.shell: |
#    set -o pipefail
#    echo {{ sambadc_admin_password }} | samba-tool dns zonecreate localhost 1.168.192.in-addr.arpa -U Administrator
#  args:
#    executable: /bin/bash
#  changed_when: true
#  tags:
#    - named

# - name: "[NAMED] - Add the host to the Reversezone."
#  ansible.builtin.shell: |
#    set -o pipefail
#    echo {{ sambadc_admin_password }} | samba-tool dns add localhost 1.168.192.in-addr.arpa 130 PTR {{ sambadc_fqdn }} -U Administrator
#  args:
#    executable: /bin/bash
#  changed_when: true
#  tags:
#    - named

# Start checking filesystem-permissions for bind9
- name: "[NAMED] - Set file permissions for the bind-files that Samba created during provisioning (bugfix 14535)."
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: root
    group: bind
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ BINDDNS_DIR }}", state: "directory", mode: "0770" }
    - { path: "{{ BINDDNS_DIR }}/dns", state: "directory", mode: "0770" }
    - { path: "{{ BINDDNS_DIR }}/dns/sam.ldb.d", state: "directory", mode: "0770" }
    - { path: "{{ BINDDNS_DIR }}/dns.keytab", state: "file", mode: "0640" }
    - { path: "{{ BINDDNS_DIR }}/dns/sam.ldb", state: "file", mode: "0660" }

- name: "[NAMED] - Listing files in BINDDNS_DIR/dns/sam.ldb.d/"
  ansible.builtin.find:
    paths: "{{ BINDDNS_DIR }}/dns/sam.ldb.d/"
    file_type: file
    patterns: "*"
  register: db_files

- name: "[NAMED] - Checking permission for BINDDNS_DIR/dns/sam.ldb.d/*"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: file
    owner: root
    group: bind
    mode: "0660"
  loop: "{{ db_files.files }}"

# Restart bind9 after setting up the domain
- name: "[NAMED] - Restart bind9 Daemon."
  ansible.builtin.service:
    name: named
    state: restarted
