---
# Setup the ntp-Daemon, compliant to samba-wiki for signing timestamps by the DC.
# Variable:
# sambadc_timezone shall contain the timezone
# sambadc_timeservers shall contain a list of maps where key is "name" and the value
# the time-server-name.
#
# NOTE: In the log of ntp a message will show up, which appears to indicate an issue.
# It may show:
# MS-SNTP signd operations currently block ntpd degrading service to all clients
# This is however normal, see: https://groups.google.com/g/linux.samba/c/KdJuhfpMUkM
- name: "[NTPD] - Set timezone."
  ansible.builtin.command: timedatectl set-timezone "{{ sambadc_timezone }}"
  changed_when: true

- name: "[NTPD] - Generate ntpd configuration for DC."
  ansible.builtin.template:
    src: templates/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: "root"
    group: "ntp"
    mode: "0440"
    force: true

- name: "{{ '[NTPD] Set permission for directory' + SAMBA_STATEDIR + '/ntp_signd .' }}"
  ansible.builtin.file:
    path: "{{ STATEDIR }}/ntp_signd"
    state: directory
    owner: "root"
    group: "ntp"
    mode: "0750"
