---
# Create share permissions for Roaming-profile directory and home-directory.
# The Roaming-profile directory for the user is automatically created upon first login of said user.
# The home-directory is not created and must be created with the creation of the user.
# In both cases, the parent-directory must have correct permissions.
# The samba-wiki suggests to set them via Windows. Here an alternative way is gone, which
# works even when the DC is also used as fileserver for those directories.
#
# vfs_xattr:ignore system acl=yes may not be set (needs proof, but sounds plausible).
# For setting security.NTACL I have taken information from here:
# https://github.com/thctlo/samba4/blob/master/samba-setup-share-folders.sh
# https://wiki.samba.org/index.php/Setting_up_a_Share_Using_Windows_ACLs

# Obtian SIDs. Not used at the moment, but might be of help later with BACKUP-function
# and preserving certain internal values, such that the DC-"BACKUP" is a true BACKUP.
# Source: https://github.com/thctlo/samba4/blob/master/samba-setup-share-folders.sh
- name: "{{ 'SHARES | Create and set permissions for share ' ~ item.path }}"
  ansible.builtin.command: wbinfo --name-to-sid "{{ name_item }}"
  register: df_cmd
  loop:
    - "\\Creator Owner"
    - "Administrator"
    - "NT Authority\\System"
    - "Domain Admins"
    - "Domain Users"
  loop_control:
    loop_var: name_item
  changed_when: false
  when: (item.type is search("isHome")) or (item.type is search("isRoaming"))
  tags:
    - shares

# - name: "SHARES | Debug"
#   ansible.builtin.debug:
#     msg: "{{ name_item | split(' ') | first }}"
#   loop: "{{ df_cmd.results | map(attribute='stdout') }}"
#   loop_control:
#     loop_var: name_item
#   when: (item.type is search("isHome")) or (item.type is search("isRoaming"))
#   tags:
#     - shares

- name: "{{ 'SHARES | Create and set ACL-permissions for share ' ~ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: "Domain Admins"
    mode: u=rwx,g=rwx,o=x
    state: directory
  when: item.type is search('isCreate')
  tags:
    - shares

# Added x-rights for Domain Computers to avoid flooding permission-denied messages to log.smbd.
- name: "{{ 'SHARES | Set isHome share ACL-permissions for ' ~ item.path }}"
  ansible.builtin.command: setfacl --set-file=- "{{ item.path }}"
  args:
    stdin: |
      # owner: root
      # group: ADN\\domain\040admins
      user::rwx
      user:root:rwx
      user:domain\040admins:rwx
      group::rwx
      group:users:r-x
      group:domain\040admins:rwx
      group:domain\040computers:x
      mask::rwx
      other::---
      default:user::rwx
      default:user:root:rwx
      default:user:domain\040admins:rwx
      default:group::---
      default:group:users:---
      default:group:domain\040admins:rwx
      default:mask::rwx
      default:other::---
  changed_when: true
  when: item.type is search("isHome")
  tags:
    - shares

# No SID needs to be inserted. When created with correct ACLs, it seems no SIDs are needed.
- name: "{{ 'SHARES | Set isHome NTACL-xattr share Permissions for ' ~ item.path }}"
  ansible.builtin.command: >
    samba-tool ntacl set
    "O:LAG:DAD:PAI(A;OICIIO;0x001f01ff;;;CO)(A;OICI;0x001f01ff;;;DA)(A;;0x001200a9;;;DU)"
    "{{ item.path }}"
  changed_when: true
  when: item.type is search("isHome")
  tags:
    - shares

# Added x-rights for Domain Computers to avoid flooding permission-denied messages to log.smbd.
- name: "{{ 'SHARES | Set isRoaming share Permissions for ' ~ item.path }}"
  ansible.builtin.command: setfacl --set-file=- "{{ item.path }}"
  args:
    stdin: |
      # owner: root
      # group: ADN\\domain\040admins
      user::rwx
      user:root:rwx
      user:NT\040Authority\\system:rwx
      user:domain\040admins:rwx
      group::rwx
      group:users:rwx
      group:NT\040Authority\\system:rwx
      group:domain\040computers:x
      group:domain\040admins:rwx
      mask::rwx
      other::---
      default:user::rwx
      default:user:root:rwx
      default:user:NT\040Authority\\system:rwx
      default:user:domain\040admins:rwx
      default:group::---
      default:group:NT\040Authority\\system:rwx
      default:group:domain\040admins:rwx
      default:mask::rwx
      default:other::---
  changed_when: true
  when: item.type is search("isRoaming")
  tags:
    - shares

# When created with right ACLs, seem no SIDs needed. Only SIDs included are generic and the same throughout provisions.
- name: "{{ 'SHARES | Set isRoaming NTACL-xattr share Permissions for ' ~ item.path }}"
  ansible.builtin.command: >
    samba-tool ntacl set
    "O:LAG:DAD:PAI(A;OICIIO;0x001f01ff;;;CO)(A;OICI;0x001f01ff;;;DA)(A;OICI;0x001f01ff;;;SY)(A;;0x001200ad;;;DU)"
    "{{ item.path }}"
  changed_when: true
  when: item.type is search("isRoaming")
  tags:
    - shares
