---
# Disable any unwanted services and enable the samba-ad-dc.service module
# Note: Afterwards DNS on the remote-host will no longer work.
#
# Source: https://dev.to/koh_sh/how-to-do-if-a-package-is-installed-do-something-with-ansible-3fhi
#         https://stackoverflow.com/questions/73483810/ansible-facts-packages-skipping-my-package-check
- name: "[SYSTEMD] - Disable services: smbd, nmbd, winbind, systemd-resolved and systemd-timesyncd prior to DC samba installation."
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  when: ansible_facts.services[ item ] is defined
  loop:
    - smbd
    - nmbd
    - winbind
    - systemd-resolved
    - systemd-timesyncd
  tags:
    - cleanup

- name: "[SYSTEMD] - Enable but stop samba-ad-dc service for samba DC installation."
  ansible.builtin.systemd:
    name: samba-ad-dc
    state: stopped
    enabled: true
    masked: false
  tags:
    - cleanup

- name: "[SYSTEMD] - Disable named/bind9 if installed, because SAMBA-INTERNAL is configured."
  ansible.builtin.systemd:
    name: named
    state: stopped
    enabled: false
    masked: true
  when:
    - sambadc_dns in [ "SAMBA_INTERNAL" ]
    - ansible_facts.services[ "named" ] is defined

- name: "[SYSTEMD] - Enable named/bind9, because BIND9_{FLATFILE, DLZ} is configured."
  ansible.builtin.systemd:
    name: named
    state: stopped
    enabled: true
    masked: false
  when: sambadc_dns in [ "BIND9_FLATFILE", "BIND9_DLZ" ]
