---
# Do some checking of the configuration provided to this ansible script before running it.
- name: "[USAGE] - Check that minimum required variables are defined and their values are correct."
  ansible.builtin.assert:
    that:
      - sambadc_dns is in [ "SAMBA_INTERNAL", "BIND9_DLZ" ]
      - sambadc_realm is defined
      - sambadc_forwarder is defined
      - sambadc_admin_password is defined
      - sambadc_type | lower is in [ "new", "join" ]
      - sambadc_timezone is defined
    msg: "There is an error setting in the minimal configuration parameters."

- name: "[USAGE] - Check interfaces and presence of bind only interfaces config parameter. (1/3)."
  ansible.builtin.meta: end_play
  when: ( ansible_facts.interfaces | length < 3 ) and ( "lo" not in ansible_facts.interfaces | lower )

- name: "[USAGE] - Check interfaces and presence of bind only interfaces config parameter. (2/3)."
  ansible.builtin.meta: end_play
  when:
    - ansible_facts.interfaces | length >= 3
    - sambadc_bind_interfaces is not defined

- name: "[USAGE] - Check interfaces and presence of bind only interfaces config parameter. (3/3)."
  ansible.builtin.meta: end_play
  when:
    - ansible_facts.interfaces | length >= 3
    - sambadc_bind_interfaces | lower not in ansible_facts.interfaces | lower

- name: "[USAGE] - Check if inventory-hostname and host-hostname match."
  ansible.builtin.meta: end_play
  when: inventory_hostname | lower != ansible_hostname | lower
