---
# Do some checking of the configuration provided to this ansible script before running it.
# However these checks require already the installed packages. Thus call it after setup_env.yml.
- name: "[USAGE-POST] - Check smb.conf-file with the configured shares included."
  when: sambadc_shares is defined
  block:
    - name: "[USAGE-POST] - Temporarily create smb.conf in /tmp folder with shares included."
      ansible.builtin.template:
        src: templates/smb.conf.j2
        dest: /tmp/smb.conf
        lstrip_blocks: true
        owner: root
        group: root
        mode: "0644"
      changed_when: false

    - name: "[USAGE-POST] - Check temporarily created smb.conf with testparm."
      ansible.builtin.command: samba-tool testparm --suppress-prompt -s /tmp/smb.conf
      register: df_cmd
      changed_when: false

    - name: "[USAGE-POST] - Check output of testparm for an error entry."
      ansible.builtin.assert:
        that:
          - df_cmd.stderr | upper is not match("UNKNOWN")
          - df_cmd.stderr | upper is not match("ERROR")
        msg: "{{ df_cmd.stderr_lines | select('match', 'ERROR', 'UNKNOWN') }}"

  always:
    - name: "[USAGE-POST] - Delete temporarily created smb.conf in /tmp."
      ansible.builtin.file:
        path: /tmp/smb.conf
        state: absent
      changed_when: false

- name: "[USAGE-POST] - Check if subnet-prefix is either 8, 16, or 24."
  ansible.builtin.meta: end_play
  when: iface.ipv4.prefix not in [ '8', '16', '24' ]
  tags:
    - dns_bind_dlz
